Assignment 1: Assigned 3 Task
sumitnegikv369/REACT-Training pull request #1
Opened 2024-03-28 09:32 UTC by sumitnegikv369

1.Create a functional component named Greeting that displays a simple "Hello, React!" message on the screen.
Import and render the Greeting component in the App component.

2.Create a functional component named UserCard that accepts the following props: name, email, and avatarURL.
Use the props to display the user's name, email, and an image (avatar) in the UserCard component.
Create multiple instances of the UserCard component with different user data.

3.Create a functional component named Weather that accepts a prop called temperature (a number).
Display a message like "It's sunny today!" if the temperature is above 25°C and "It's cold today!" if the temperature is below 10°C.
Import and render the Weather component in the App component with different temperature values.

2024-03-29 12:27 UTC, bhavya-goel requested changes

2024-03-29 12:27 UTC, bhavya-goel commented on myapp/src/day1/Question1/index.js
> +const index = () => {
simply export the components from index file

2024-03-29 12:27 UTC, bhavya-goel commented on myapp/src/day1/Question1/question1.module.css
> +div{
remove .module from the file name

2024-03-29 12:31 UTC, bhavya-goel requested changes

2024-03-29 12:31 UTC, bhavya-goel commented on myapp/src/day1/Question6/index.js
> +        display: 'flex',
move this to it's css

2024-04-02 05:20 UTC, sumitnegikv369 commented
updated the day 1 assignment

2024-04-02 09:05 UTC, bhavya-goel requested changes

2024-04-02 09:05 UTC, bhavya-goel commented on myapp/src/day1/Question1/index.js
> +import './styles.css'
import css in the actual component itself

2024-04-02 12:31 UTC, bhavya-goel approved these changes

2024-04-02 12:31 UTC, merged